services:
  postgres:
    image: ankane/pgvector:latest  # PostgreSQL with pgvector pre-installed
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: ./server
    container_name: server
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.server
    ports:
      - "3001:3001"

  client:
    build: ./client 
    container_name: client
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=server:3001
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  postgres_data:
